version: '3.8'

services:
  backend:
    build:
      context: ./back-end
    ports:
      - "8800:8800"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_NAME=mydatabase
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontendcadpessoas
    ports:
      - "3000:3000"
    depends_on:
      - backend


  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
